### ISSUE TITLE
align split with gaps in partition

### ISSUE THREAD

**Issue by stiatragul** [hhandika/segul#24]
**Is your feature request related to a problem? Please describe.**
The problem I have is sometimes I want to chop up ("split") a region of an alignment using align split but I'm only interested in a few charset. 

**Describe the solution you'd like**
Allow users to split the alignment into several files according to the name of the locus as specified in the partition file but allow gaps. 

**Describe alternatives you've considered**
AMAS split 
custom r scripts using seqinr

**Additional context**
Currently, align split will throw an error if the partition file has Start position not the next position after the previous end position. So I end up having to manually code in "filler_regions" to get the program to run. 

For example I should be able to use this as the input partition file.

```nexus
#Nexus
begin set
  charset 12s = 44-97 ;
  charset trna_Val1 = 978-1046 ;
  charset 16s = 1047-2615 ;
  charset ND4 = 10088-11449 ;
  charset ND5 = 11617-13416 ;
  charset ND6 = 13417-13885 ;
  charset CYTB = 13958-14926 ;
end;
```

**Comment by hhandika** [comment]
Hi @stiatragul! Sorry for the delay to response. Yes. this is possible using the `--skip-checking` flag. I tested your partition example using my dataset. It worked well. 

Example command:

```
segul align split -i .\Align-Concat\Align-Concat.nex -I .\Align-Concat\test.nex --skip-checking
```
