### ISSUE TITLE
sequence rename bug error: unexpected argument '-n' found

### ISSUE THREAD

**Issue by stiatragul** [hhandika/segul#25]
**Describe the bug**
Unable to provide new_names.csv file for running `segul sequence rename`. Getting error: unexpected argument '-n'. 

Expected command according to the (documentation)[https://www.segul.app/docs/cli-usage/rename]:
`segul sequence rename -d [alignment-dir] -f [sequence-format-keyword] -n [file-path-to-IDs]`

**To Reproduce**

```
❯ segul
An ultrafast and memory efficient tool for phylogenomics

Usage: segul [OPTIONS] <COMMAND>

Commands:
  read       Sequence read analyses
  contig     Contiguous sequence analyses
  align      Alignment analyses
  partition  Alignment partition conversion
  sequence   Sequence analyses
  help       Print this message or the help of the given subcommand(s)

Options:
      --log <LOG>  Log file path [default: segul.log]
  -h, --help       Print help
  -V, --version    Print version
❯ segul sequence rename -d ahe_subset -f fasta -n ../ahe_topotest/new_names.csv --dry-run
error: unexpected argument '-n' found

Usage: segul sequence rename [OPTIONS]

For more information, try '--help'.
```

**Expected behavior**
Command to take `-n` new_names.csv 

**Please complete the following information:**
 - OS: Ubuntu 
- Version 22.04.4 LTS

**Additional context**
Also when passing `--name`
```
❯ segul sequence rename --dir ahe_subset --name ../ahe_topotest/new_names.csv
error: unexpected argument '--name' found

Usage: segul sequence rename <--dir <PATH>|--input <INPUT>...|--force>

For more information, try '--help'.
```

**Comment by hhandika** [comment]
Hi @stiatragul! Sorry for the doc issues. We made significant changes recently. It allows for regular expression now too. The new command should be `--replace-id`.

**Comment by stiatragul** [comment]
That's fantastic @hhandika !
